# Generated by Django 2.0.5 on 2018-05-30 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lineattend', '0002_auto_20180529_0956'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Calendar',
        ),
    ]
