# Generated by Django 2.0.5 on 2018-06-12 01:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('lineattend', '0003_delete_calendar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('my_set', models.IntegerField(default=0, verbose_name='自分のセット数')),
                ('opponent_set', models.IntegerField(default=0, verbose_name='相手のセット数')),
                ('date', models.DateTimeField(verbose_name='日時')),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=255, verbose_name='ユーザーID')),
                ('name', models.CharField(max_length=255, verbose_name='名前')),
            ],
        ),
        migrations.AddField(
            model_name='match',
            name='my_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_user', to='lineattend.User'),
        ),
        migrations.AddField(
            model_name='match',
            name='opponent_user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opponent_user', to='lineattend.User'),
        ),
    ]
