# Generated by Django 2.0.5 on 2018-06-12 05:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lineattend', '0004_auto_20180612_1058'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='hiragana_name',
            field=models.CharField(default='', max_length=255, verbose_name='読み方'),
        ),
        migrations.AlterField(
            model_name='user',
            name='name',
            field=models.CharField(default='', max_length=255, verbose_name='名前'),
        ),
    ]
